[MOSIP-37445] updated docker-build.yml
Signed-off-by: Rakshith B <79500257+Rakshithb1@users.noreply.github.com>

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -55,6 +55,16 @@ jobs:
           echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
           echo "${{ toJSON(inputs) }}"
 
+      - name: Check Dockerfile for forbidden organizations and tags
+        run: |
+          cd ${{ inputs.SERVICE_LOCATION }}
+          if grep -E "FROM (mosipdev|mosipqa)/" Dockerfile || grep -E "FROM .*:(latest|develop)" Dockerfile; then
+            echo "Error: Dockerfile contains forbidden base image from mosipdev or mosipqa or uses 'latest' or 'develop' tag."
+            exit 1
+          else
+            echo "Dockerfile check passed: No forbidden organizations or tags found."
+          fi
+    
       - name: Get version info from pom
         if: ${{ contains(inputs.NPM_BUILD, 'false') && ( inputs.BUILD_ARTIFACT != 'false' )  && ( inputs.ONLY_DOCKER == false ) }}
         id: getPomVersion
